const cardImgs = {
  clubs: {
    1: require('./Clubs/Ace.png'),
    2: require('./Clubs/Two.png'),
    3: require('./Clubs/Three.png'),
    4: require('./Clubs/Four.png'),
    5: require('./Clubs/Five.png'),
    6: require('./Clubs/Six.png'),
    7: require('./Clubs/Seven.png'),
    8: require('./Clubs/Eight.png'),
    9: require('./Clubs/Nine.png'),
    10: require('./Clubs/Ten.png'),
    11: require('./Clubs/Jack.png'),
    12: require('./Clubs/Queen.png'),
    13: require('./Clubs/King.png'),
  },
  spades: {
    1: require('./Spades/Ace.png'),
    2: require('./Spades/Two.png'),
    3: require('./Spades/Three.png'),
    4: require('./Spades/Four.png'),
    5: require('./Spades/Five.png'),
    6: require('./Spades/Six.png'),
    7: require('./Spades/Seven.png'),
    8: require('./Spades/Eight.png'),
    9: require('./Spades/Nine.png'),
    10: require('./Spades/Ten.png'),
    11: require('./Spades/Jack.png'),
    12: require('./Spades/Queen.png'),
    13: require('./Spades/King.png'),
  },
  diamonds: {
    1: require('./Diamonds/Ace.png'),
    2: require('./Diamonds/Two.png'),
    3: require('./Diamonds/Three.png'),
    4: require('./Diamonds/Four.png'),
    5: require('./Diamonds/Five.png'),
    6: require('./Diamonds/Six.png'),
    7: require('./Diamonds/Seven.png'),
    8: require('./Diamonds/Eight.png'),
    9: require('./Diamonds/Nine.png'),
    10: require('./Diamonds/Ten.png'),
    11: require('./Diamonds/Jack.png'),
    12: require('./Diamonds/Queen.png'),
    13: require('./Diamonds/King.png'),
  },
  hearts: {
    1: require('./Hearts/Ace.png'),
    2: require('./Hearts/Two.png'),
    3: require('./Hearts/Three.png'),
    4: require('./Hearts/Four.png'),
    5: require('./Hearts/Five.png'),
    6: require('./Hearts/Six.png'),
    7: require('./Hearts/Seven.png'),
    8: require('./Hearts/Eight.png'),
    9: require('./Hearts/Nine.png'),
    10: require('./Hearts/Ten.png'),
    11: require('./Hearts/Jack.png'),
    12: require('./Hearts/Queen.png'),
    13: require('./Hearts/King.png'),
  },
  back: require('./red_back.png'),
} as const;

export default cardImgs;
